packages/vue-next/gulp/template/icon.tsx
packages/vue-next/package.json
packages/vue-next/src/iconfont/icon.tsx
packages/vue-next/src/iconfont/props/props.ts
packages/vue-next/src/svg-sprite/svg-sprite.tsx
packages/vue-next/src/utils/use-size-props.ts

1. fix re-render after props change
2. fix duplicate of class name

fix vue next iconfont

---

packages/angular/projects/tdesign-icons-angular/package.json
packages/angular/projects/tdesign-icons-angular/src/lib/tdesign-icons-angular.component.ts
packages/react/CHANGELOG.md
packages/react/package.json
packages/react/src/icon.tsx
packages/react/src/iconfont/iconfont.tsx
packages/react/src/svg-sprite/type.ts
packages/react/src/util/use-common-classname.ts
packages/vue-next/CHANGELOG.md
packages/vue-next/package.json
packages/vue-next/src/iconfont/icon.tsx
packages/vue-next/src/svg-sprite/svg-sprite.tsx
packages/vue-next/src/utils/use-common-classname.ts
packages/vue/CHANGELOG.md
packages/vue/package.json
packages/vue/src/iconfont/icon.tsx
packages/vue/src/svg-sprite/svg-sprite.tsx
packages/vue/src/utils/check-url-and-load.ts
packages/vue/src/utils/use-common-classname.ts

1. 处理icon 中尺寸改为`medium`的问题
2. 修复`icons-vue`、`icons-vue-next` SSR的问题

fix icon medium size

---

packages/angular/projects/tdesign-icons-angular/CHANGELOG.md
packages/angular/projects/tdesign-icons-angular/package.json

- 更新 tdesign-icons-angular 版本 0.0.2 -> 0.0.3，添加 CHANGELOG 说明

更新 tdesign-icons-angular 版本 0.0.2 -> 0.0.3，添加 CHANGELOG

---

packages/vue-next/src/utils/check-url-and-load.ts

fix:vue3 ssr报错修复

---

packages/angular/gulp/template/icon.component.ts
packages/angular/projects/tdesign-icons-angular/src/lib/tdesign-icons-angular.component.ts

https://github.com/angular/angular/issues/24034 此处反馈 Angular 下的组件有问题，需要将 HostBinding 相关变量可访问性从 protected 设置为 public
- fix(angular): 将 HostBinding 相关 protected 变量设置为 public

fix(angular): 将 HostBinding 相关变量可访问性从 protected 设置为 public

---

packages/angular/projects/tdesign-icons-angular/CHANGELOG.md
packages/angular/projects/tdesign-icons-angular/package.json

chore(angular): publish 0.1.1

---

packages/react/src/icon.tsx

`React`版本icon透传`ref`，否则跟`popup`组件组合使用时会出现异常行为。
https://codesandbox.io/s/tdesign-react-demo-forked-usrdml

fix(react): add ref & fix warning and error with popup

---

gulp/generate-type-map.ts
packages/react/.gitignore
packages/react/gulp/index.ts
packages/react/package.json
packages/react/src/index.ts

chore(react): support global icon config

---

svg/flag.svg

- fix(iconfont): 修复`flag` 图标在iconfont中的渲染异常

chore: fix flag icon render in iconfont

---

svg/minus-rectangle-fill.svg

- feat: 新增`minus-rectangle-fill`图标

feat: add minus-rectangle-fill icon

---

packages/angular/projects/tdesign-icons-angular/CHANGELOG.md
packages/angular/projects/tdesign-icons-angular/package.json
packages/angular/projects/tdesign-icons-angular/src/lib/tdesign-icons-angular.component.ts
packages/react/CHANGELOG.md
packages/react/package.json
packages/react/src/iconfont/iconfont.tsx
packages/react/src/svg-sprite/svg-sprite.tsx
packages/svg/package.json
packages/view/package.json
packages/vue-next/CHANGELOG.md
packages/vue-next/package.json
packages/vue-next/src/iconfont/icon.tsx
packages/vue-next/src/svg-sprite/svg-sprite.tsx
packages/vue/CHANGELOG.md
packages/vue/package.json
packages/vue/src/iconfont/icon.tsx
packages/vue/src/svg-sprite/svg-sprite.tsx

chore: release new version

---

gulp/generate-entry.ts
gulp/generate-icon-font.ts
gulp/generate-icons.ts
gulp/generate-manifest.ts
gulp/generate-sprite.ts
gulp/svg-info-check.ts
gulp/transform.ts

chore: gulp dir format

---

packages/view/gulp/generate-view-map.ts

feat: support any color replace

---

packages/view/gulp/generate-view-map.ts

Reverts Tencent/tdesign-icons#49

Revert "feat: support any color replace"

---

gulp/generate-manifest.ts

feat: add path in manifest

---

pnpm-lock.yaml

chore: update dependencies lock

---

package.json
pnpm-lock.yaml
pnpm-workspace.yaml

fix: workspace config

---

packages/react/CHANGELOG.md
packages/react/package.json
packages/svg/CHANGELOG.md
packages/svg/package.json
packages/view/CHANGELOG.md
packages/view/package.json
packages/vue-next/CHANGELOG.md
packages/vue-next/package.json
packages/vue/CHANGELOG.md
packages/vue/package.json

chore: release new versions

---

package.json
packages/angular/projects/tdesign-icons-angular/package.json
packages/react/package.json
packages/svg/package.json
packages/view/package.json
packages/vue-next/package.json
packages/vue/package.json

- chore: workspaces is not required in package.json when using pnpm
- chore: add repository info in each packages

chore: remove workspaces from package.json

---

gulp/generate-manifest.ts

manifest 新增path 影响 vite 等开发工具开发环境发起的请求 字段暂时没有广泛使用场景 从流水线中移除 
- fix: 修复 manifest 新增path 影响 vite 等开发工具构建请求的问题

fix: manifest effects chunk

---

packages/view/CHANGELOG.md
packages/view/package.json
packages/view/src/IconView.vue
packages/view/src/vars.css

- fix(icon-view): fix variables missing in some case 

fix(view): variables missing

---

packages/react/CHANGELOG.md
packages/react/package.json
packages/view/CHANGELOG.md
packages/view/package.json
packages/view/src/IconView.vue
packages/vue-next/CHANGELOG.md
packages/vue-next/package.json
packages/vue/CHANGELOG.md
packages/vue/package.json
pnpm-lock.yaml

fix: icon view wrap style

---

packages/view/src/IconView.vue
packages/view/src/manifest.js

feat: support display all searched icons

---

pnpm-lock.yaml
types/index.d.ts

chore: fix react native project

---

packages/react-native/CHANGELOG.md
packages/react-native/package.json

- chore: release react-native icon 0.0.1

chore: release react-native icon 0.0.1

---

packages/web-components/CHANGELOG.md
packages/web-components/package.json

- chore: release web-components 0.1.1

chore: release web-components 0.1.1

---

packages/web-components/CHANGELOG.md
packages/web-components/package.json

- chore: release web-components 0.1.2

chore: release web-components 0.1.2

---

packages/vue-next/src/index.ts
packages/vue-next/src/utils/with-install.ts

fix(vue-next): fix umd usage

---

packages/vue-next/CHANGELOG.md
packages/vue-next/package.json

chore: release tdesign-icons-vue-next 0.2.5

---

packages/web-components/CHANGELOG.md
packages/web-components/package.json

- chore: release tdesign-icons-web-components 0.1.4

chore: release tdesign-icons-web-components 0.1.4

---

packages/web-components/CHANGELOG.md
packages/web-components/package.json

chore: release tdesign-icons-web-components 0.1.5

---

packages/web-components/package.json

fix(webC): fix sideEffects config 

---

packages/view/CHANGELOG.md
packages/view/package.json
packages/web-components/CHANGELOG.md
packages/web-components/package.json

chore: version release

---

packages/react/CHANGELOG.md
packages/react/package.json
packages/react/src/iconfont/iconfont.tsx
packages/react/src/svg-sprite/svg-sprite.tsx
packages/view/CHANGELOG.md
packages/view/package.json
packages/vue-next/CHANGELOG.md
packages/vue-next/package.json
packages/vue-next/src/iconfont/icon.tsx
packages/vue-next/src/svg-sprite/svg-sprite.tsx
packages/vue/CHANGELOG.md
packages/vue/package.json
packages/vue/src/iconfont/icon.tsx
packages/vue/src/svg-sprite/svg-sprite.tsx
packages/web-components/CHANGELOG.md
packages/web-components/package.json

chore: release version

---

.husky/pre-commit

chore(pre-commit): use pnpm

---

.github/workflows/preview-publish.yml
.github/workflows/pull-request.yml
pnpm-lock.yaml

chore: add icon preview ci

---

packages/view/src/IconView.vue

windows 会卡 ,优化网站的icon搜索，添加 `debounce` 和使用 `shallowRef`
- perf: optimize site search icon

perf: optimize site search icon

---

gulp/svgo.ts

- fix: fix path data convert bug

fix: fix convert path data bug

---

.github/workflows/auto-pr-tdesign-react.yml
.github/workflows/auto-pr-tdesign-vue-next.yml

ci(auto-pr): vue-next and react, add pnpm action

---

packages/react/CHANGELOG.md
packages/react/package.json

- feat: tdesign-icons-react support React 19

chore: release tdesign-icons-react 0.5.0

---

packages/react/src/icon.tsx
packages/vue-next/gulp/template/icon.tsx
packages/vue/src/icon.tsx

- fix: 增加 fill:none 内联样式，避免新版本图标受老版本样式污染的问题

fix: fix compatibility with previous version
